### ISSUE TITLE
React router dom V6 implementation 

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/hacktoberfest-gym-guru#1]
1. Implement react router dom in the project 

[react-router](https://reactrouter.com/en/main/start/overview)

2. make pages 

- Home
- Gallery
- Plans 
- About 
- Join Now

**Comment by thezeeshann** [comment]
@sahilsingh7735 assign me. i really want to work on this issue

**Comment by sahilsingh7735** [comment]
@thezeeshann sure go ahead.

**Comment by sahilsingh7735** [comment]
@thezeeshann  Just a reminder before releasing PR take a pull.

**Comment by thezeeshann** [comment]
@sahilsingh7735 done. Do I create a pull request?

**Comment by sahilsingh7735** [comment]
Make a separate branch and raise a PR

**Comment by thezeeshann** [comment]
@sahilsingh7735 okay
